### PR TITLE
Initialize FullPathMapper from base struct and sites struct

### PR DESCRIPTION
**Pull request by acrutt**

### CODE REVIEW

**Comment by jmmshn** [comment]
@acrutt  can you figure out why the test case is failing?

**Comment by acrutt** [comment]
Yes, I can look at this more closely.

**Comment by acrutt** [comment]
@jmmshn I finished making the additional fixes needed but there is one minor conflict that I don't have permission to resolve.

**Comment by jmmshn** [comment]
@acrutt  Thanks for all the documentation updates they are really helpful.

I went through the PR more carefully and I now understand why the test case broke and how you fixed it.
It looks like you are fundamentally changing how the sites that can move are defined, which removed the original code's ability to create the `only_sites` attribute.  I think a better way will be to feed a list of site indices (maybe a subset of the sites that are the migrating species) this will still allow the code to function as it did before for cases where you are just interested in the normal migration graph.

Also, it might make more sense to PR this directly into pymatgen-diffusion since it pull in my fork already.
I would suggest doing a documentation/variable name change update first before the new logic is introduced, and you can use this time to figure out exactly how that new logic should be implemented.

**Comment by acrutt** [comment]
The `only_sites` attribute is now called the `sites_structure` attribute. I did some renaming of the attributes to be clearer with the FullPathMapper changes but otherwise my intention was for these two attributes to be the same. Can the conflict be resolved by replacing `self.only_sites` with `self.sites_structure` in creating the s_graph attribute? Or is there something preventing this replacement?

I'm not sure I agree that providing the sites as a list of site indices is the way to go. I think it would create an unnecessary additional step, increase the odds of a user error, and makes some helpful functionality more difficult (e.g. if I have all the insertion sites in a separate structure, I can merge similar sites that are very close together). I rather not make this change unless there are other benefits I'm missing.

**Comment by jmmshn** [comment]
> The only_sites attribute is now called the sites_structure attribute. I did some renaming of the attributes to be clearer with the FullPathMapper changes but otherwise my intention was for these two attributes to be the same. Can the conflict be resolved by replacing self.only_sites with self.sites_structure in creating the s_graph attribute? Or is there something preventing this replacement?

My problem is not with changing the name my problem is with completely getting rid of the ability to generate this graph from the imputer structure and migrating species along. <-- This is the reason the test failed.  The current fix does not seem to actually address the cause of this break but rather changes the test completely to avoid raising an error.

> I'm not sure I agree that providing the sites as a list of site indices is the way to go. I think it would create an unnecessary additional step, increase the odds of a user error, and makes some helpful functionality more difficult (e.g. if I have all the insertion sites in a separate structure, I can merge similar sites that are very close together). I rather not make this change unless there are other benefits I'm missing.

The benefit is that if we are not using this selective migration of specific ions. Then the code has lost a very basic capability that it originally had.   And causing upstream things to break for new features is will generally lead to more unforeseen problems down the line.

Either way, this should be a materialsvirtuallab/pymatgen-diffusion PR now so I will close this PR for now.

**Comment by acrutt** [comment]
Now it sounds like there is a qualm with the originally proposed change to how the FullPathMapper is constructed. Are you saying you are not ok with changing the input from one structure that contains both the base and inserted/mobile sites?

If someone wishes to start with a combined structure of both the base and inserted/mobile sites it's just about two lines of code to convert that into two structures if you are able to distinguish the inserted/mobile sites by specie. So this didn't seem like a burdensome change to me.

**Comment by jmmshn** [comment]
So using the index was just a suggestion after reading the code.  You can still just use a structure but to make it less invasive you can have the site structure as an optional parameter, so if it provided you use it if it is not provided create the structure using the old method that you deleted.
That will allow the code to do what you need and not break any of the original usage cases.

**Comment by acrutt** [comment]
Ok, I can add that back in and make a new pull request

**Pull request closed without merging**
